#!/bin/bash

### SETUP REQUIRED ###
# Before starting to use this script, some setup of gh-pages branch is required
# * create _layouts
# * move index.html to _layouts
# * edit index.html to remove the main-content section content and replace it with {{content}}
# * touch index.md and add it to git tree
# * commit everything and run this script
######################

# Layout prefix is prepended to each markdown file synced
###################################################################
LAYOUT_PREFIX='---\nlayout: index\n---\n'

# Sync the README.md in master to index.md adding jekyll header
###################################################################
echo -e $LAYOUT_PREFIX > index.md
git show master:README.md >> index.md
git commit index.md -m "Sync README.md in master branch to index.md in gh-pages"
    
git push 
